spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hibernate_inheritance_mapping
    username: spring-boot
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true